config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  get 'main/about'

  get 'main/contact'

  get 'main/form'

  root 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def form
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imagicase</title>



    <% if params[:controller] + params[:action] == "main index" %>
    <!-- Global Site Tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-102339305-3"></script>
    <script>
     window.dataLayer = window.dataLayer || [];
     function gtag(){dataLayer.push(arguments)};
     gtag('js', new Date());

     gtag('config', 'UA-102339305-3');
    </script>
<% end %>


    <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- Latest compiled and minified JavaScript -->
    <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path %>"><img src="<%= asset_path 'imagicase_new.png' %>" alt="" class="logo"></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      </li>
    </ul>

    <ul class="nav navbar-var navbar-left">
      <li>
        <a href="<%= main_about_path %>" class="link">
          About
        </a>
      </li>

      <li class="nav-item">
        <a href="<%= main_contact_path %>" class="link">
          Contact
        </a>
      </li>

    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">EN<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="javascript:void(0)">ES</a></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>


    <article>
      <div class="container"><%= yield %></div>
    </article>

  <footer >
    <div class="footer-bottom">
      <div class="container">
        <p class="pull-left">
          <img src="<%= asset_path 'logo_startup' %>" alt="" class="splogo">
        </p>
        <div class="pull-right">
          <ul class="nav nav-pills social">
            <li><a href="http://twitter.com/dorapalfi"><i class="fa fa-twitter"></i></a></li>
            <li><a href="http://github.com/doripalfi"><i class="fa fa-github"></i></a></li>
            <li><a href="http://linkedin.com/in/dorapalfi"><i class="fa fa-linkedin"></i></a></li>
            <li><a href="http://doripalfi.tumblr.com"><i class="fa fa-tumblr"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/main/about.html.erb
<div class="col-md-6 col-sm-12">
	<br>
	<br>
	<br>
	<br>
	<br>
	<img class="dora_img" src="<%= asset_path 'dora_small_pic.jpg' %>" alt="">
</div>

<div class="col-md-6 col-sm-12">

	<h1 style="color: #696969;">I'm Dora Palfi!</h1>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero itaque nisi, voluptate expedita labore sunt eligendi reiciendis aliquam corporis minima sequi earum eos incidunt error, illo quibusdam a nihil aliquid?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque quo illo numquam maxime tenetur fugiat, ad suscipit possimus cupiditate praesentium, omnis, distinctio laborum aut ea sit voluptate! Voluptas, distinctio, necessitatibus.
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus sapiente dolorem cupiditate magni sequi quaerat natus aliquid quisquam. Similique veritatis ratione accusantium obcaecati qui est eum fugiat atque, quia nobis.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis cumque maiores iste delectus nulla voluptatibus voluptatem eius, labore voluptates dignissimos consequatur vitae necessitatibus deleniti fugiat fugit iusto minus blanditiis tenetur!
</div>

app/views/main/contact.html.erb
<h1>Main#contact</h1>

app/views/main/form.html.erb
<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/slim-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
   #mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
   /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
      We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//create-squared.us14.list-manage.com/subscribe/post?u=bbefa2f9e88ca0772f5e401e1&amp;id=888a36074b" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
  <div id="mc_embed_signup_scroll">
   <label for="mce-EMAIL">Subscribe to our mailing list</label>
   <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
  <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
  <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_bbefa2f9e88ca0772f5e401e1_888a36074b" tabindex="-1" value=""></div>
  <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
  </div>
</form>
</div>

<!--End mc_embed_signup-->

app/views/main/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="space"></div>
<h4 class="col-md-6"><img class="logo_center" src="<%= asset_path 'imagicase_new' %>" alt="">
<br>
<br>
<br>
<br>
</h4>


<div class="right col-md-6">
	<h4 class="right">
<span class="green-btn">
	COMING SOON: THE BEST WAY TO LEARN CODING
</span>
<br>
<br>
<br>
 <span class="purple-btn">
 	DESIGNED BY GIRLS WITH GIRLS IN MIND
 </span>

	<br>
	<br>
	<br>
 <a href="<%= main_form_path %>" class="button biliboard electronic" class="center">
	NOTIFY ME!
</a>
</h4>
<br>
<br>
<br>
<br>
<br>
</div>